/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSubmissionsIndexRouteImport } from './routes/_app/submissions/index'
import { Route as AppSubmissionsSubmissionIdRouteImport } from './routes/_app/submissions/$submissionId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmissionsIndexRoute = AppSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmissionsSubmissionIdRoute =
  AppSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/submissions/': typeof AppSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/submissions': typeof AppSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/_app/submissions/': typeof AppSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/submissions/$submissionId' | '/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/submissions/$submissionId' | '/submissions'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/submissions/$submissionId'
    | '/_app/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/submissions/': {
      id: '/_app/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AppSubmissionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/submissions/$submissionId': {
      id: '/_app/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof AppSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSubmissionsSubmissionIdRoute: typeof AppSubmissionsSubmissionIdRoute
  AppSubmissionsIndexRoute: typeof AppSubmissionsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSubmissionsSubmissionIdRoute: AppSubmissionsSubmissionIdRoute,
  AppSubmissionsIndexRoute: AppSubmissionsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
