/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReviewersIndexRouteImport } from './routes/_app/reviewers/index'
import { Route as AppArticlesIndexRouteImport } from './routes/_app/articles/index'
import { Route as AppUsersCreateRouteImport } from './routes/_app/users/create'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppReviewersCreateRouteImport } from './routes/_app/reviewers/create'
import { Route as AppReviewersReviewerIdRouteImport } from './routes/_app/reviewers/$reviewerId'
import { Route as AppArticlesSubmissionIdRouteImport } from './routes/_app/articles/$submissionId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReviewersIndexRoute = AppReviewersIndexRouteImport.update({
  id: '/reviewers/',
  path: '/reviewers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersCreateRoute = AppUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReviewersCreateRoute = AppReviewersCreateRouteImport.update({
  id: '/reviewers/create',
  path: '/reviewers/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReviewersReviewerIdRoute = AppReviewersReviewerIdRouteImport.update({
  id: '/reviewers/$reviewerId',
  path: '/reviewers/$reviewerId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesSubmissionIdRoute = AppArticlesSubmissionIdRouteImport.update({
  id: '/articles/$submissionId',
  path: '/articles/$submissionId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/articles/$submissionId': typeof AppArticlesSubmissionIdRoute
  '/reviewers/$reviewerId': typeof AppReviewersReviewerIdRoute
  '/reviewers/create': typeof AppReviewersCreateRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/create': typeof AppUsersCreateRoute
  '/articles/': typeof AppArticlesIndexRoute
  '/reviewers/': typeof AppReviewersIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/articles/$submissionId': typeof AppArticlesSubmissionIdRoute
  '/reviewers/$reviewerId': typeof AppReviewersReviewerIdRoute
  '/reviewers/create': typeof AppReviewersCreateRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/create': typeof AppUsersCreateRoute
  '/articles': typeof AppArticlesIndexRoute
  '/reviewers': typeof AppReviewersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/articles/$submissionId': typeof AppArticlesSubmissionIdRoute
  '/_app/reviewers/$reviewerId': typeof AppReviewersReviewerIdRoute
  '/_app/reviewers/create': typeof AppReviewersCreateRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/create': typeof AppUsersCreateRoute
  '/_app/articles/': typeof AppArticlesIndexRoute
  '/_app/reviewers/': typeof AppReviewersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$submissionId'
    | '/reviewers/$reviewerId'
    | '/reviewers/create'
    | '/users/$userId'
    | '/users/create'
    | '/articles/'
    | '/reviewers/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$submissionId'
    | '/reviewers/$reviewerId'
    | '/reviewers/create'
    | '/users/$userId'
    | '/users/create'
    | '/articles'
    | '/reviewers'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/articles/$submissionId'
    | '/_app/reviewers/$reviewerId'
    | '/_app/reviewers/create'
    | '/_app/users/$userId'
    | '/_app/users/create'
    | '/_app/articles/'
    | '/_app/reviewers/'
    | '/_app/settings/'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reviewers/': {
      id: '/_app/reviewers/'
      path: '/reviewers'
      fullPath: '/reviewers/'
      preLoaderRoute: typeof AppReviewersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles/': {
      id: '/_app/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/create': {
      id: '/_app/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AppUsersCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reviewers/create': {
      id: '/_app/reviewers/create'
      path: '/reviewers/create'
      fullPath: '/reviewers/create'
      preLoaderRoute: typeof AppReviewersCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reviewers/$reviewerId': {
      id: '/_app/reviewers/$reviewerId'
      path: '/reviewers/$reviewerId'
      fullPath: '/reviewers/$reviewerId'
      preLoaderRoute: typeof AppReviewersReviewerIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles/$submissionId': {
      id: '/_app/articles/$submissionId'
      path: '/articles/$submissionId'
      fullPath: '/articles/$submissionId'
      preLoaderRoute: typeof AppArticlesSubmissionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppArticlesSubmissionIdRoute: typeof AppArticlesSubmissionIdRoute
  AppReviewersReviewerIdRoute: typeof AppReviewersReviewerIdRoute
  AppReviewersCreateRoute: typeof AppReviewersCreateRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersCreateRoute: typeof AppUsersCreateRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
  AppReviewersIndexRoute: typeof AppReviewersIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppArticlesSubmissionIdRoute: AppArticlesSubmissionIdRoute,
  AppReviewersReviewerIdRoute: AppReviewersReviewerIdRoute,
  AppReviewersCreateRoute: AppReviewersCreateRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersCreateRoute: AppUsersCreateRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
  AppReviewersIndexRoute: AppReviewersIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
